/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kddlzartfawqjnrafzdb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZGx6YXJ0ZmF3cWpucmFmemRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk1NTQyNTMsImV4cCI6MjA5NTEzMDI1M30.ajqoH99BVN-fDZ6Gd-mClHdw_PjjIhSRJOxEKVdws9I"